### ISSUE TITLE
[Bug]: example.com/my-account/addresses state field is disable

### ISSUE THREAD

**Issue by ashishkpaul** [vuestorefront-community/prestashop#60]
### Expected Behavior

**State** field should be active at example.com/**my-account/addresses** 

### Actual Behavior

same as title and crash after sime time

![Screenshot_2022-11-04_10-22-46](https://user-images.githubusercontent.com/16308863/199890742-dd19ef13-2e1e-4783-9100-de7b20de3ea1.png)

![Screenshot_2022-11-04_10-13-15](https://user-images.githubusercontent.com/16308863/199890789-f607531c-4ed1-4ec3-a7bd-c71dcdc407ad.png)

### Steps to reproduce

sign in then go to **my-account/addresses**  page

### What version of PrestaShop integration are you using?

v1.1.0

### What version of Node.js are you using?

v14.19.3

### What browser (and version) are you using?

Chrome, Firefox

### What operating system (and version) are you using?

Debian

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samberrry** [comment]
thanks for reporting. 
I think you changed the logic, because we should see country, but there is not country in this photo. 
![Screen Shot 2022-11-07 at 11 25 48 AM](https://user-images.githubusercontent.com/20775532/200363117-29c54050-28b0-436c-8538-d9b88dadddcd.png)

Also, some countries have state, and some others do not have. The state will change based on the selected country, just like the default prestashop behavior.

**Comment by samberrry** [comment]
Please re-open it, if you see the issue on clean install.
